### ISSUE TITLE
Crash with basemod

### ISSUE THREAD

**Issue by Mimaju** [daviscook477/BaseMod#114]
Receiving this error when trying to load just basemod. Anyone have an idea what to do?

javassist.NotFoundException: com.megacrit.cardcrawl.events.thecity.Vampires
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:206)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:174)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:239)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Unknown Source)

**Comment by kiooeht** [comment]
The weekly update 39 broke BaseMod and a lot of mods. BaseMod has since updated, but made a lot of major changes that other mods will need to update for before they'll work.
