### ISSUE TITLE
Crashed in event fights

### ISSUE THREAD

**Issue by lionpkqq** [daviscook477/BaseMod#115]
Exception: java.lang.ClassCastException: basemod.CustomEventRoom cannot be cast to com.megacrit.cardcrawl.rooms.MonsterRoom
04:18:02.811 ERROR core.CardCrawlGame> Exception caught
java.lang.ClassCastException: basemod.CustomEventRoom cannot be cast to com.megacrit.cardcrawl.rooms.MonsterRoom
	at basemod.patches.com.megacrit.cardcrawl.rooms.AbstractRoom.StartBattleHook.Insert(StartBattleHook.java:21) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:239) ~[?:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:51) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2700) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:892) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:464) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**(This is likely related to the Make StartBattleHook work when loading a save (gogo81745) update in my opinion. )**

**Comment by kiooeht** [comment]
Hotfixed https://github.com/daviscook477/BaseMod/releases/tag/v3.0.1
