### ISSUE TITLE
Crash in version v3.4.0 when starting a new run: NoSuchFieldError 'enabledMods'

### ISSUE THREAD

**Issue by M-TGH** [daviscook477/BaseMod#132]
Encountering a crash at the beginning of a new run, using versions:

ModTheSpire: v3.2.0
BaseMod: v3.4.0
SlayTheSpire: 09-18-2018

No other mods enabled.

Full exception stack trace:
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: enabledMods
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchFieldError: enabledMods
	at basemod.patches.com.megacrit.cardcrawl.ui.panels.TopPanel.TopPanelPatches$SetPlayerNamePatch.Postfix(TopPanelPatches.java:207)
	at com.megacrit.cardcrawl.ui.panels.TopPanel.setPlayerName(TopPanel.java:211)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.<init>(AbstractDungeon.java:337)
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:50)
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1370)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

EDIT:

Assume it's due to [this change](https://github.com/daviscook477/BaseMod/compare/v3.3.0...master#diff-ccbb526d433240325230054de655e787R207), however I don't know anything about modding the game otherwise I'd try my luck at a PR.

**Comment by kiooeht** [comment]
You're running an old version of the game. BaseMod v3.4.0 is for Slay the Spire 09-27-2018

**Comment by M-TGH** [comment]
Oh, my bad. Interesting Steam hasn't told me to update yet, so I assumed it was up to date. Guess I'll have to restart steam.
