### ISSUE TITLE
Ethereal Issue is back + Unlock issue

### ISSUE THREAD

**Issue by Lunaraia** [daviscook477/BaseMod#14]
Ethereal Issue is back in full, not 100% sure what broke it again.

java.lang.ArrayIndexOutOfBoundsException: 2
	at com.megacrit.cardcrawl.powers.IntangiblePower.updateDescription(IntangiblePower.java:57) ~[?:?]
	at com.megacrit.cardcrawl.powers.IntangiblePower.<init>(IntangiblePower.java:29) ~[?:?]
	at com.megacrit.cardcrawl.monsters.thebeyond.Nemesis.takeTurn(Nemesis.java:89) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.monsters.MonsterGroup.takeTurn(MonsterGroup.java:126) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:270) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:143) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:241) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2435) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:782) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:374) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Game closed.

this is with the latest (downloaded just before taking it out on another run)

**Comment by daviscook477** [comment]
Nemesis issue will be fixed in next patch. I figured it out.
