### ISSUE TITLE
BaseMod won't to work

### ISSUE THREAD

**Issue by gabbus98** [daviscook477/BaseMod#169]
`Running with debug mode turned ON...

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (07-12-2018)
 - ModTheSpire (3.6.2)
Mod list:
 - basemod (5.4.0)
 - fruitymod-sts (1.0.3)

Begin patching...
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.screens.SingleCardViewPopup.OpenFix$OpenTextureFix:
No method named [loadPortraitImg] found on
class [com.megacrit.cardcrawl.screens.SingleCardViewPopup]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:264)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:185)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:199)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)`

How can I resolve this?

I tryed with a lot of different version of all mods, help me pls.

**Comment by kiooeht** [comment]
> Slay the Spire (07-12-2018)

You're running an extremely old version of the game. The latest is 12-20-2018. You need to update to latest version for mods to work.
