### ISSUE TITLE
Not sure where to put this as it contains errors for both Mods

### ISSUE THREAD

**Issue by Lunaraia** [daviscook477/BaseMod#18]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:32)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:154)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:71)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at basemod.BaseMod.subscribeToPostInitialize(BaseMod.java:2067)
	at fruitymod.FruityMod.<init>(FruityMod.java:354)
	at fruitymod.FruityMod.initialize(FruityMod.java:401)
	... 8 more

**Comment by daviscook477** [comment]
I'm pretty sure this one was my fault with making a bugged release of BaseMod yesterday. Try the latest one @Lunaraia and see if that fixes it. It should still be broken because of the weekly patch 15 but it should be a different issue.

**Comment by Lunaraia** [comment]
I found the error, the solution was actually surprisingly simple, turns out the Load Order was to blame, just tested with the newest version and I crashed, then I started it up again and thought about disabling BaseMod to see if it was Fruity that was at fault, then I noticed that Basemod was in a different location in the mod list so I moved it upward using Click and Drag and BOOM the game works.

Addendum: Load Order Matters
