### ISSUE TITLE
Startup Crash -  NoClassDefFound for powers/Absorbpowers

### ISSUE THREAD

**Issue by CryorusTheDragon** [daviscook477/BaseMod#19]
Downloaded the latest releases of ModTheSpire , Base Mod and Fruity Mod. 
Spire is in non-beta mode
Getting this error on startup : 

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:32)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:154)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:71)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/powers/AbsorbPower
	at basemod.BaseMod.initializePowerMap(BaseMod.java:568)
	at basemod.BaseMod.initialize(BaseMod.java:367)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.megacrit.cardcrawl.powers.AbsorbPower
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	... 10 more

**Comment by daviscook477** [comment]
New Weekly patch just dropped https://steamcommunity.com/app/646570.
BaseMod will be updated to work with the patch within a day or two.

**Comment by daviscook477** [comment]
Fixed here https://github.com/daviscook477/BaseMod/releases/tag/v2.1.2
