### ISSUE TITLE
Game won't launch after the update

### ISSUE THREAD

**Issue by NoNick96** [daviscook477/BaseMod#200]
This is what the log shows. Nothing is happening after.

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (01-23-2019)
 - ModTheSpire (3.8.3)
Mod list:
 - basemod (5.12.0)
 - stslib (1.14.0)
 - infinitespire (0.15.1)
 - ReplayTheSpireMod (1.3.25)
 - hubris (0.21.4)

Begin patching...
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.MissingParamTypesException: Patch basemod.patches.com.megacrit.cardcrawl.powers.CloneablePowersPatch$SlowPowerPatch
Patching .<ctor>:
Has overloads and no paramtypes defined
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:243)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:185)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:269)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:265)
	at java.lang.Thread.run(Thread.java:748)

**Comment by NoNick96** [comment]
Fixed by the author of Replay the Spire
