### ISSUE TITLE
TestMod PurpleClad crashes

### ISSUE THREAD

**Issue by bug-sniper** [daviscook477/BaseMod#209]
I'm only running BaseMod and TestMod. With no changes to the mods, I get this error after winning the first battle and before I can choose a card.

[mts_process_launch.log](https://github.com/daviscook477/BaseMod/files/2974672/mts_process_launch.log)

Exception: java.lang.IllegalArgumentException: n must be positive
01:22:48.147 ERROR core.CardCrawlGame> Exception caught
java.lang.IllegalArgumentException: n must be positive
	at com.badlogic.gdx.math.RandomXS128.nextLong(RandomXS128.java:110) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.math.RandomXS128.nextInt(RandomXS128.java:99) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.random.Random.random(Random.java:52) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.cards.CardGroup.getRandomCard(CardGroup.java:570) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getCard(AbstractDungeon.java:1883) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getRewardCards(AbstractDungeon.java:1833) ~[?:?]
	at com.megacrit.cardcrawl.rewards.RewardItem.<init>(RewardItem.java:161) ~[?:?]
	at com.megacrit.cardcrawl.screens.CombatRewardScreen.setupItemReward(CombatRewardScreen.java:90) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.screens.CombatRewardScreen.open(CombatRewardScreen.java:375) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:387) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2552) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by LZHHZLLZH** [comment]
Hi, have you solve this crash? I have met the same problem after winning the first battle.
