### ISSUE TITLE
Crash upon card pickup

### ISSUE THREAD

**Issue by AvangionQ** [daviscook477/BaseMod#228]
Not sure what's causing this, but it happens with each floor ...

01:03:23.874 INFO basemod.BaseMod> publishMaxHPChange
Exception: java.util.ConcurrentModificationException
01:03:23.876 ERROR core.CardCrawlGame> Exception caught
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_144]
	at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2648) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by AvangionQ** [comment]
Every single time I try to pick up a card, the game crashes ... loads correctly, allows me to pick up the cards, proceed to next combat, crash again with card pickup ...

01:07:18.439 INFO basemod.BaseMod> publishMaxHPChange
Exception: java.util.ConcurrentModificationException
01:07:18.443 ERROR core.CardCrawlGame> Exception caught
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_144]
	at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2648) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.
