### ISSUE TITLE
Latest Beta update broke the mod

### ISSUE THREAD

**Issue by gingsi** [daviscook477/BaseMod#274]
Hi,

Since the latest beta patch a couple of days ago I get the following error when trying to start:

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (11-17-2020) BETA
 - ModTheSpire (3.18.0)
Mod list:
 - basemod (5.25.0)
 - superfastmode (1.0.7)

Begin patching...
Patching enums...Done.
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.screens.DeathScreen.ForceUnlock:
No method named [calculateUnlockProgress] found on
class [com.megacrit.cardcrawl.screens.DeathScreen]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:411)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:336)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:386)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:269)
	at java.lang.Thread.run(Thread.java:748)

Please consider fixing as not having superfastmode makes me fall asleep.

Edit: Same error when I only run basemod and nothing else (no superfastmode).

Best

**Comment by kiooeht** [comment]
The Slay the Spire beta has now been released to main branch and BaseMod updated to be compatible.
