### ISSUE TITLE
Do not launch. String out of range -1

### ISSUE THREAD

**Issue by CodelessHeart** [daviscook477/BaseMod#300]
I launch only base mod on mod the spire 3.20.0
```
`ModVersion Info:
 - Java version (1.8.0_201)
 - Slay the Spire (12-22-2020)
 - ModTheSpire (3.20.0)
Mod list:
 - basemod (5.32.2)

Begin patching...
Patching enums...Done.
Finding core patches...
Finding patches...
Patching Overrides...
Injecting patches...Done.
Compiling patched classes...Done.
Busting enums...Done.

Setting isModded = true...Done.

Adding ModTheSpire to version...Done.

Initializing mods...
 - BaseMod
   - basemod.BaseMod
libgdx version 1.9.5
13:35:37.259 INFO basemod.BaseMod> initializeGson
13:35:37.327 INFO basemod.BaseMod> initializeTypeMaps
13:35:37.336 INFO basemod.BaseMod> Registered MonsterStrings
13:35:37.347 INFO basemod.BaseMod> Registered PowerStrings
13:35:37.355 INFO basemod.BaseMod> Registered CardStrings
13:35:37.358 INFO basemod.BaseMod> Registered RelicStrings
13:35:37.360 INFO basemod.BaseMod> Registered EventStrings
13:35:37.377 INFO basemod.BaseMod> Registered PotionStrings
13:35:37.380 INFO basemod.BaseMod> Registered CreditStrings
13:35:37.383 INFO basemod.BaseMod> Registered TutorialStrings
13:35:37.385 INFO basemod.BaseMod> Registered KeywordStrings
13:35:37.387 INFO basemod.BaseMod> Registered ScoreBonusStrings
13:35:37.389 INFO basemod.BaseMod> Registered CharacterStrings
13:35:37.393 INFO basemod.BaseMod> Registered UIStrings
13:35:37.399 INFO basemod.BaseMod> Registered OrbStrings
13:35:37.404 INFO basemod.BaseMod> Registered StanceStrings
13:35:37.407 INFO basemod.BaseMod> Registered RunModStrings
13:35:37.409 INFO basemod.BaseMod> Registered BlightStrings
13:35:37.414 INFO basemod.BaseMod> Registered AchievementStrings
13:35:37.415 INFO basemod.BaseMod> initializePowerMap

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:47)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:442)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:273)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at basemod.BaseMod.initializePowerMap(BaseMod.java:692)
	at basemod.BaseMod.initialize(BaseMod.java:371)
	... 8 more`
```

**Comment by kiooeht** [comment]
I was unable to reproduce the crash, but I've added some error checking that should stop it from crashing for you.
