### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by billdagou** [daviscook477/BaseMod#302]
Hi there, I followed https://github.com/daviscook477/BaseMod/wiki/Starting-Your-Mod to setup my first mod, but got the NullPointerException.

ModVersion Info:
 \- Java version (1.8.0_144)
 \- Slay the Spire (12-22-2020)
 \- ModTheSpire (3.20.0)
Mod list:
 \- basemod (5.32.3)
 \- Test mod (1.0.0)

......

Setting isModded = true...Done.

Adding ModTheSpire to version...Done.

Initializing mods...
 \- BaseMod
   \- basemod.BaseMod
libgdx version 1.9.5
03:34:28.697 INFO basemod.BaseMod> initializeGson
03:34:28.720 INFO basemod.BaseMod> initializeTypeMaps
03:34:28.723 INFO basemod.BaseMod> Registered MonsterStrings
03:34:28.726 INFO basemod.BaseMod> Registered PowerStrings
03:34:28.727 INFO basemod.BaseMod> Registered CardStrings
03:34:28.727 INFO basemod.BaseMod> Registered RelicStrings
03:34:28.727 INFO basemod.BaseMod> Registered EventStrings
03:34:28.728 INFO basemod.BaseMod> Registered PotionStrings
03:34:28.728 INFO basemod.BaseMod> Registered CreditStrings
03:34:28.728 INFO basemod.BaseMod> Registered TutorialStrings
03:34:28.729 INFO basemod.BaseMod> Registered KeywordStrings
03:34:28.729 INFO basemod.BaseMod> Registered ScoreBonusStrings
03:34:28.730 INFO basemod.BaseMod> Registered CharacterStrings
03:34:28.732 INFO basemod.BaseMod> Registered UIStrings
03:34:28.732 INFO basemod.BaseMod> Registered OrbStrings
03:34:28.734 INFO basemod.BaseMod> Registered StanceStrings
03:34:28.735 INFO basemod.BaseMod> Registered RunModStrings
03:34:28.735 INFO basemod.BaseMod> Registered BlightStrings
03:34:28.736 INFO basemod.BaseMod> Registered AchievementStrings
03:34:28.738 INFO basemod.BaseMod> initializePowerMap
03:34:29.401 INFO basemod.BaseMod> initializeUnderscorePowerIDs
   \- 737ms
 \- Test mod
   \- billdagou.Test
java.lang.NullPointerException
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:41)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:442)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:273)
	at java.lang.Thread.run(Thread.java:748)

**Comment by billdagou** [comment]
Sorry, my fault. It should be `modid` in `ModTheSpire.json` while I was using `mod` by mistake. The mod is working now.
