### ISSUE TITLE
no meathod to calculate progress?

### ISSUE THREAD

**Issue by derplord0323** [daviscook477/BaseMod#308]
Running with debug mode turned ON...

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (null)
 - ModTheSpire (3.6.3)
Mod list:
 - basemod (5.5.0)
 - stslib (1.10.0)
 - ReplayTheSpireMod (1.5.0)

Begin patching...
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.screens.DeathScreen.ForceUnlock:
No method named [calculateUnlockProgress] found on
class [com.megacrit.cardcrawl.screens.DeathScreen]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:264)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:185)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:199)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Bagels1** [comment]
Ok looks like for 3 years nobody replied to this repeated problem?

**Comment by banchl** [comment]
I had the same problem as you. The latest release version of ModTheSpire is only 3.6.3.
You need to package the latest code version 3.30.3 locally.
Or you can try the files I packed
https://github.com/banchl/ModTheSpire/releases/tag/v3.30.3
