### ISSUE TITLE
Conspire crash

### ISSUE THREAD

**Issue by adman120** [daviscook477/BaseMod#330]
COPYING FROM STEAM FOURMS
"The new update broke Conspire. Since that mod hasn't been updated in years, is this something you can fix?
Log:

Begin patching...
Patching enums...Done.
Finding core patches...
Finding patches...
java.lang.reflect.UndeclaredThrowableException
at com.sun.proxy.$Proxy3.clz(Unknown Source)
at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:434)
at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:382)
at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:398)
at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:285)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: [basemod.patches.com.megacrit.cardcrawl.events.NoteForYourself.MissingCard](https://steamcommunity.com/linkfilter/?url=http://basemod.patches.com.megacrit.cardcrawl.events.NoteForYourself.MissingCard)
at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:112)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:96)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at javassist.bytecode.annotation.MemberValue.loadClass(MemberValue.java:56)
at javassist.bytecode.annotation.ClassMemberValue.getValue(ClassMemberValue.java:89)
at javassist.bytecode.annotation.AnnotationImpl.invoke(AnnotationImpl.java:151)
... 6 more"

**Comment by kiooeht** [comment]
This has been fixed (04225c402699f9e34b14f76661ba88bf0a7f88c9).
