### ISSUE TITLE
litteraly just started getting mods and this is the error i get 

### ISSUE THREAD

**Issue by dparted** [daviscook477/BaseMod#357]
i have tried multiple versions of basemod and tried with and without other mods, ive looked and seen other people with identicle error messages but they all had different solutions with none of them working for me

ModVersion Info:
 - Java version (1.8.0_341)
 - Slay the Spire (null)
 - ModTheSpire (3.6.3)
Mod list:
 - basemod (5.3.4)
 - stslib (1.10.0)
 - Friendly_Minions_0987678 (0.1.2)

Begin patching...
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.screens.DeathScreen.ForceUnlock:
No method named [calculateUnlockProgress] found on
class [com.megacrit.cardcrawl.screens.DeathScreen]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:264)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:185)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:199)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Unknown Source)

**Comment by Bagels1** [comment]
I get the exact same, yet nobody replied 2 years ago, is this a dead end?
