### ISSUE TITLE
Basemod not working???

### ISSUE THREAD

**Issue by RamrarTheKing** [daviscook477/BaseMod#61]
Hi I really want to play with mods yet for some reason the actual startup isnt working. I have v2.6.0 of modthespire, i have opted out of the latest beta branch as apparently that causes problems and I have literally tried every basemod package and none of them work.
This is what keeps popping up. Any help would be appreciated.

Java version: 1.8.0_171
Slay the Spire version: 05-10-2018
ModTheSpire version: 2.6.0
Mod list: JuggerMod, basemod (2.4.0), 
Finding core patches...
Finding patches...
ERROR: No method [getPotion] found on class [com.megacrit.cardcrawl.gashapon.NeowReward]
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: com.megacrit.cardcrawl.screens.mainMenu.CardLibraryScreen.render: Location matching given description could not be found for patch
	at com.evacipated.cardcrawl.modthespire.lib.LineFinder.findInOrder(LineFinder.java:30)
	at basemod.patches.com.megacrit.cardcrawl.screens.mainMenu.CardLibraryScreen.EverythingFix$Render$Locator.Locate(EverythingFix.java:258)
	at com.evacipated.cardcrawl.modthespire.patcher.LocatorInfo.findLines(LocatorInfo.java:18)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:265)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:170)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:185)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:189)
	at java.lang.Thread.run(Unknown Source) 
commit close #61

**Comment by Problembeloeser** [comment]
Which StS Patch ur on, BaseMod currently seems not to have a Release for Week 24, in which the potion system got lil rework. In your error message is shown, that there occurs a problem with potion methods, so i recommend you to wait until the release for week 24 comes out

**Comment by RamrarTheKing** [comment]
ah okay yeah my slaythespire is fully updated, I did have a feeling it might have been because of the huge potion update done recently, just wanted to make sure though. Thanks, it was probably that.

**Comment by Problembeloeser** [comment]
pls close this issue, it was only from temporary manner

**Comment by RamrarTheKing** [comment]
Oh yeah jeez completely forgot sorry will do now.
