### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by Asger91** [daviscook477/BaseMod#74]
Here is the Error that comes when I try to start the game.

Mod list: basemod (2.12.1), betamode (1), betterrewardsmod (3.0.0), constructmod (0.5.2), customclimb (0.3.2), MadScienceMod (0.1.5), ReplayTheSpireMod, superfastmode (0.8.1), witchmod (0.9), 
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: com.megacrit.cardcrawl.core.CardCrawlGame.update: Location matching given description could not be found for patch
	at com.evacipated.cardcrawl.modthespire.lib.LineFinder.findInOrder(LineFinder.java:30)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PreUpdateHook$Locator.Locate(UpdateHooks.java:40)
	at com.evacipated.cardcrawl.modthespire.patcher.LocatorInfo.findLines(LocatorInfo.java:18)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:265)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:170)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:185)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:189)
	at java.lang.Thread.run(Unknown Source)

deactivating all mods didn't help.
And when BaseMod was the last active Mod the same error still came

**Comment by kiooeht** [comment]
You didn't include the very start of the log, so I can't be sure, but I'm fairly certain you're using the beta branch. BaseMod does not support the beta branch. If you want to use mods, switch to the main branch of the game.

**Comment by Scooters1206** [comment]
I am encountering the same issue. Clean install. Was going to try modding tonight for the first time. Log as follows:

Java version: 1.8.0_171
Slay the Spire version: 06-14-2018
ModTheSpire version: 2.6.0
Mod list: basemod (2.12.1), 
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: com.megacrit.cardcrawl.core.CardCrawlGame.update: Location matching given description could not be found for patch
	at com.evacipated.cardcrawl.modthespire.lib.LineFinder.findInOrder(LineFinder.java:30)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PreUpdateHook$Locator.Locate(UpdateHooks.java:40)
	at com.evacipated.cardcrawl.modthespire.patcher.LocatorInfo.findLines(LocatorInfo.java:18)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:265)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:170)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:185)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:189)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kiooeht** [comment]
Because the game just updated with changes that break BaseMod. It will take time before it gets updated to work with the latest patch.

**Comment by Scooters1206** [comment]
Understood, thank you for the quick response.
