### ISSUE TITLE
more issues with the new patch

### ISSUE THREAD

**Issue by Lunaraia** [daviscook477/BaseMod#77]
Begin patching...
Finding core patches...
Finding patches...
javassist.NotFoundException: com.megacrit.cardcrawl.screens.mainMenu.RelicViewScreen
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:206)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:174)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:229)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Unknown Source)

only thing that pops up, game doens't even start

**Comment by KongMD-Steam** [comment]
I can't reproduce this crash. BaseMod works for me. What's in your modlist, @Lunaraia?

**Comment by kiooeht** [comment]
As @KongMD-Steam asked, what mods are you trying to use?
I know Replay The Spire has this exact error at the moment.

**Comment by Lunaraia** [comment]
that wouls probably be the reason then as I use Replaythespire will try without it and get back to you
