### ISSUE TITLE
Some kind of exception happened when I picked up a card

### ISSUE THREAD

**Issue by Lunaraia** [daviscook477/BaseMod#8]
Exception: java.lang.NullPointerException
01:40:34.711 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(Unknown Source) ~[?:1.8.0_162]
	at java.util.Scanner.<init>(Unknown Source) ~[?:1.8.0_162]
	at com.megacrit.cardcrawl.cards.AbstractCard.initializeDescription(AbstractCard.java:387) ~[?:?]
	at fruitymod.cards.Brainstorm.upgrade(Brainstorm.java:56) ~[FruityMod.jar:?]
	at com.megacrit.cardcrawl.relics.ToxicEgg2.onObtainCard(ToxicEgg2.java:21) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.vfx.FastCardObtainEffect.update(FastCardObtainEffect.java:49) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2516) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:782) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:374) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Game closed.

**Comment by daviscook477** [comment]
Will be fixed with the next release. Thanks for the heads up
