### ISSUE TITLE
Unable to launch the modded game

### ISSUE THREAD

**Issue by SirHaesslich** [daviscook477/BaseMod#96]
I had only BaseMod enabled, and did not even make it to opening the game window. Here is the log:

javassist.CannotCompileException: [source error] no such field: tmp
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:132)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:146)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:146)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:233)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Thread.java:748)
Caused by: compile error: no such field: tmp
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:221)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:735)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 7 more

**Comment by kiooeht** [comment]
You're running on the beta branch of the game. Mod The Spire and BaseMod do not support the beta branch. Switch to the main branch if you want to play with mods.
