### ISSUE TITLE
Issue in Endless Mode, not sure wheter it's ConstructMod or BaseMod related, so posting in both

### ISSUE THREAD

**Issue by Lunaraia** [daviscook477/BaseMod#97]
Exception: java.util.ConcurrentModificationException
16:52:58.148 ERROR core.CardCrawlGame> Exception caught
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_171]
at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_171]
at basemod.BaseMod.publishPostDungeonInitialize(BaseMod.java:1887) ~[?:?]
at basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.PostDungeonInitializeHook.Postfix(PostDungeonInitializeHook.java:9) ~[BaseMod.jar:?]
at com.megacrit.cardcrawl.dungeons.AbstractDungeon.initializeRelicList(AbstractDungeon.java:1766) ~[?:?]
at com.megacrit.cardcrawl.dungeons.Exordium.(Exordium.java:52) ~[?:?]
at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1291) ~[?:?]
at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:810) ~[?:?]
at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:415) [?:?]
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
16:52:59.157 INFO core.CardCrawlGame> PAUSE()
16:52:59.157 INFO core.CardCrawlGame> Game shutting down...
16:53:01.573 INFO helpers.File> Failed to copy file=D:\SteamLibrary\steamapps\common\SlayTheSpire\preferences\THE_CONSTRUCT_MOD
java.nio.channels.ClosedByInterruptException: null
at java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source) ~[?:1.8.0_171]
at sun.nio.ch.FileChannelImpl.size(Unknown Source) ~[?:1.8.0_171]
at java.nio.file.Files.readAllBytes(Unknown Source) ~[?:1.8.0_171]
at com.megacrit.cardcrawl.helpers.File.validateWrite(File.java:140) ~[desktop-1.0.jar:?]
at com.megacrit.cardcrawl.helpers.File.copyAndValidate(File.java:97) [desktop-1.0.jar:?]
at com.megacrit.cardcrawl.helpers.File.save(File.java:49) [desktop-1.0.jar:?]
at com.megacrit.cardcrawl.helpers.FileSaver.consume(FileSaver.java:42) [desktop-1.0.jar:?]
at com.megacrit.cardcrawl.helpers.FileSaver.run(FileSaver.java:25) [desktop-1.0.jar:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
16:53:01.574 INFO helpers.File> java.lang.InterruptedException: sleep interrupted

**Comment by kiooeht** [comment]
It looks like one of the mods you were using tried to unsubscribe itself from the `PostDungeonInitialize` hook while BaseMod was performing that hook.

I looked at the other issue you made on Construct (https://github.com/Moocowsgomoo/StS-ConstructMod/issues/19) and that's a long list of mods you were using, the problem could of been caused by any of them.

Let me know if this ever happens again and what mods you were using, for all we know the mod that caused the problem has already fixed it.

**Comment by Lunaraia** [comment]
A-OK will keep you notified, want me to include the exception stuff if it happens again?

**Comment by kiooeht** [comment]
Yes, please do.
